version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/data-trading-backend
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: ./scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: ./scripts/after_install.sh
      runas: root
  ApplicationStop:
    - location: ./scripts/application_stop.sh
      runas: ubuntu
  ApplicationStart:
    - location: ./scripts/application_start.sh
      runas: ubuntu